import { Languages, MessageCircleMore, Send, WifiOff } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { getLocale, type Locale } from "@/lib/i18n";
import { requireWorkspace } from "@/lib/workspace";
import { createAdminClient } from "@/lib/supabase/admin";
import { resolveWhatsAppAccessToken } from "@/lib/whatsapp";
import { markConversationRead, sendWhatsAppMessage } from "../actions";

type Copy={title:string;sub:string;waTitle:string;waHint:string;inbox:string;count:(n:number)=>string;newConversation:string;noSummary:string;reply:string;connect:string;send:string;empty:string;emptyHint:string;select:string;messages:string;markRead:string;inbound:string;outbound:string;internal:string;noMessages:string};
const copy:Record<Locale,Copy>={
 ar:{title:"المحادثات",sub:"صندوق موحد لرسائل العملاء عبر القنوات المتصلة.",waTitle:"موصل WhatsApp ينتظر بيانات Meta",waHint:"بعد إضافة رقم الأعمال والمفاتيح سيبدأ استقبال الرسائل وإرسالها من هذه الشاشة.",inbox:"صندوق الوارد",count:n=>`${n} محادثة`,newConversation:"محادثة جديدة",noSummary:"لا يوجد ملخص بعد",reply:"اكتب ردًا للعميل...",connect:"أكمل ربط Meta أولًا",send:"إرسال",empty:"لا توجد محادثات بعد",emptyHint:"ستظهر رسائل القنوات المتصلة هنا.",select:"اختر محادثة لعرض سجل الرسائل",messages:"سجل الرسائل",markRead:"تحديد كمقروء",inbound:"العميل",outbound:"الفريق",internal:"داخلي",noMessages:"لا توجد رسائل في هذه المحادثة بعد"},
 tr:{title:"Konuşmalar",sub:"Bağlı kanallardaki müşteri mesajları için birleşik gelen kutusu.",waTitle:"WhatsApp bağlantısı Meta bilgilerini bekliyor",waHint:"İşletme numarası ve anahtarlar eklendiğinde mesajlar bu ekrandan alınıp gönderilebilir.",inbox:"Gelen kutusu",count:n=>`${n} konuşma`,newConversation:"Yeni konuşma",noSummary:"Henüz özet yok",reply:"Müşteriye yanıt yazın...",connect:"Önce Meta bağlantısını tamamlayın",send:"Gönder",empty:"Henüz konuşma yok",emptyHint:"Bağlı kanallardaki mesajlar burada görünür.",select:"Mesaj geçmişini görmek için bir konuşma seçin",messages:"Mesaj geçmişi",markRead:"Okundu olarak işaretle",inbound:"Müşteri",outbound:"Ekip",internal:"Dahili",noMessages:"Bu konuşmada henüz mesaj yok"},
 en:{title:"Conversations",sub:"One inbox for customer messages across connected channels.",waTitle:"The WhatsApp connector is waiting for Meta credentials",waHint:"Once the business number and keys are configured, messages can be received and sent from this screen.",inbox:"Inbox",count:n=>`${n} conversation${n===1?"":"s"}`,newConversation:"New conversation",noSummary:"No summary yet",reply:"Write a reply to the customer...",connect:"Complete the Meta connection first",send:"Send",empty:"No conversations yet",emptyHint:"Messages from connected channels will appear here.",select:"Select a conversation to view its message history",messages:"Message history",markRead:"Mark as read",inbound:"Customer",outbound:"Team",internal:"Internal",noMessages:"No messages in this conversation yet"}
};
type Props={searchParams:Promise<{error?:string;success?:string;conversation?:string}>};
export default async function ConversationsPage({searchParams}:Props){
 const [params,locale,{supabase,organizationId}]=await Promise.all([searchParams,getLocale(),requireWorkspace()]); const t=copy[locale];
 const {data}=await supabase.from("conversations").select("id, channel, status, customer_language, summary, unread_count, last_message_at, leads(full_name)").eq("organization_id",organizationId).order("last_message_at",{ascending:false,nullsFirst:false});
 const selectedId=/^[0-9a-f-]{36}$/i.test(params.conversation??"")?params.conversation:null;
 const selected=(data??[]).find(item=>item.id===selectedId)??null;
 const {data:messages}=selected?await supabase.from("messages").select("id, direction, sender_type, original_text, translated_text, original_language, translated_language, delivery_status, sent_at, created_at").eq("organization_id",organizationId).eq("conversation_id",selected.id).order("created_at",{ascending:true}).limit(200):{data:null};
 let whatsappReady=false; if(process.env.META_APP_SECRET&&process.env.WHATSAPP_VERIFY_TOKEN&&process.env.SUPABASE_SECRET_KEY){const admin=createAdminClient();const {data:connections}=await admin.from("whatsapp_connections").select("access_token_env_key").eq("organization_id",organizationId).eq("status","active");whatsappReady=Boolean(connections?.some(connection=>resolveWhatsAppAccessToken(connection.access_token_env_key)));}
 return <main className="content"><PageHeader title={t.title} subtitle={t.sub}/>{params.error&&<div className="alert error">{params.error}</div>}{params.success&&<div className="alert success">{params.success}</div>}{!whatsappReady&&<div className="connector-notice"><WifiOff size={18}/><div><strong>{t.waTitle}</strong><span>{t.waHint}</span></div></div>}
 <div className="inbox-grid"><section className="panel"><div className="panel-head"><div><h2>{t.inbox}</h2><p>{t.count(data?.length??0)}</p></div><Languages size={20}/></div><div className="cards-list">{(data??[]).map(item=>{const lead=Array.isArray(item.leads)?item.leads[0]:item.leads;return <a className={`conversation-card ${selected?.id===item.id?"active":""}`} href={`/conversations?conversation=${item.id}`} key={item.id}><div className="conversation-row"><div className="channel-icon"><MessageCircleMore size={19}/></div><div><strong>{lead?.full_name??t.newConversation}</strong><span>{item.summary||t.noSummary}</span></div><div className="conversation-side"><span>{item.channel}</span>{item.unread_count>0&&<b>{item.unread_count}</b>}</div></div></a>})}{!data?.length&&<div className="empty-state"><MessageCircleMore size={30}/><strong>{t.empty}</strong><span>{t.emptyHint}</span></div>}</div></section>
 <section className="panel conversation-thread">{!selected?<div className="empty-state"><MessageCircleMore size={30}/><strong>{t.select}</strong></div>:<><div className="panel-head"><div><h2>{t.messages}</h2><p>{selected.channel}</p></div>{selected.unread_count>0&&<form action={markConversationRead}><input type="hidden" name="conversationId" value={selected.id}/><button className="secondary-button compact" type="submit">{t.markRead}</button></form>}</div><div className="message-thread">{(messages??[]).map(message=><article className={`message-bubble ${message.direction}`} key={message.id}><small>{message.direction==="inbound"?t.inbound:message.direction==="outbound"?t.outbound:t.internal}</small><p>{message.translated_text||message.original_text||"—"}</p>{message.translated_text&&message.original_text&&message.translated_text!==message.original_text&&<details><summary>{message.original_language??"original"}</summary><p>{message.original_text}</p></details>}<time>{new Date(message.sent_at||message.created_at).toLocaleString(locale==="ar"?"ar":locale==="tr"?"tr-TR":"en")}</time></article>)}{!messages?.length&&<div className="empty-state"><span>{t.noMessages}</span></div>}</div>{selected.channel==="whatsapp"&&<form className="reply-form thread-reply" action={sendWhatsAppMessage}><input type="hidden" name="conversationId" value={selected.id}/><input name="body" maxLength={4096} placeholder={whatsappReady?t.reply:t.connect} disabled={!whatsappReady} required/><button type="submit" disabled={!whatsappReady} aria-label={t.send}><Send size={17}/></button></form>}</>}</section></div></main>;
}
