import Link from "next/link";
import { ArrowLeft, CalendarClock, CircleDollarSign, MessageCircleMore, TrendingUp, UserPlus, UsersRound } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { getLocale, type Locale } from "@/lib/i18n";
import { requireWorkspace } from "@/lib/workspace";

type StatusKey = "new" | "contacted" | "qualified" | "appointment" | "negotiation" | "won" | "lost" | "disqualified";
type DashboardCopy = {
  hello:string; sub:string; add:string; total:string; month:string; qualified:string; ready:string; overdue:string; rescue:string; open:string; reply:string; pipeline:string; active:string; recent:string; priority:string; all:string; customer:string; source:string; status:string; score:string; manual:string; first:string; journey:string; upcoming:string; timezone:string; client:string; none:string; calendar:string;
  statuses: Record<StatusKey,string>;
};
const copy: Record<Locale, DashboardCopy> = {
  ar: { hello:"صباح الخير 👋", sub:"هذه صورة فريقك الآن، من أول رسالة حتى إغلاق الصفقة.", add:"عميل جديد", total:"إجمالي العملاء", month:"هذا الشهر", qualified:"عملاء مؤهلون", ready:"جاهزون للمتابعة", overdue:"متابعات متأخرة", rescue:"فرص تحتاج إنقاذ", open:"محادثات مفتوحة", reply:"تحتاج ردًا", pipeline:"قيمة المسار", active:"الصفقات النشطة", recent:"أحدث العملاء", priority:"الأولوية حسب النتيجة وآخر نشاط", all:"عرض الكل", customer:"العميل", source:"المصدر", status:"الحالة", score:"النتيجة", manual:"يدوي", first:"ابدأ بإضافة أول عميل", journey:"ستظهر رحلة المبيعات هنا مباشرة.", upcoming:"المواعيد القادمة", timezone:"بتوقيت إسطنبول", client:"عميل", none:"لا توجد مواعيد قادمة", calendar:"فتح التقويم", statuses:{new:"جديد",contacted:"تم التواصل",qualified:"مؤهل",appointment:"موعد",negotiation:"تفاوض",won:"مغلق بنجاح",lost:"مفقود",disqualified:"غير مؤهل"}},
  tr: { hello:"Günaydın 👋", sub:"Ekibinizin ilk mesajdan anlaşmanın kapanışına kadar güncel görünümü.", add:"Yeni müşteri", total:"Toplam müşteri", month:"Bu ay", qualified:"Nitelikli müşteriler", ready:"Takibe hazır", overdue:"Geciken takipler", rescue:"Kurtarılması gereken fırsatlar", open:"Açık konuşmalar", reply:"Yanıt bekliyor", pipeline:"Pipeline değeri", active:"Aktif fırsatlar", recent:"Son müşteriler", priority:"Skor ve son aktiviteye göre öncelik", all:"Tümünü gör", customer:"Müşteri", source:"Kaynak", status:"Durum", score:"Skor", manual:"Manuel", first:"İlk müşterinizi ekleyin", journey:"Satış yolculuğu burada görünecek.", upcoming:"Yaklaşan randevular", timezone:"İstanbul saati", client:"Müşteri", none:"Yaklaşan randevu yok", calendar:"Takvimi aç", statuses:{new:"Yeni",contacted:"İletişim kuruldu",qualified:"Nitelikli",appointment:"Randevu",negotiation:"Görüşme",won:"Kazanıldı",lost:"Kaybedildi",disqualified:"Uygun değil"}},
  en: { hello:"Good morning 👋", sub:"Your team's live view from first message to closed deal.", add:"New lead", total:"Total leads", month:"This month", qualified:"Qualified leads", ready:"Ready for follow-up", overdue:"Overdue follow-ups", rescue:"Opportunities to rescue", open:"Open conversations", reply:"Need a reply", pipeline:"Pipeline value", active:"Active deals", recent:"Recent leads", priority:"Prioritized by score and recent activity", all:"View all", customer:"Customer", source:"Source", status:"Status", score:"Score", manual:"Manual", first:"Add your first lead", journey:"The sales journey will appear here.", upcoming:"Upcoming appointments", timezone:"Istanbul time", client:"Customer", none:"No upcoming appointments", calendar:"Open calendar", statuses:{new:"New",contacted:"Contacted",qualified:"Qualified",appointment:"Appointment",negotiation:"Negotiation",won:"Won",lost:"Lost",disqualified:"Disqualified"}},
};
const statusLabel=(statuses:DashboardCopy["statuses"], status:string)=>status in statuses ? statuses[status as StatusKey] : status;
export default async function DashboardPage() {
  const [{ supabase, organizationId: orgId }, locale] = await Promise.all([requireWorkspace(), getLocale()]);
  const t = copy[locale];
  const [leadsCount, qualifiedCount, openConversations, pipeline, recentLeads, upcoming, overdueFollowUps] = await Promise.all([
    supabase.from("leads").select("id", { count: "exact", head: true }).eq("organization_id", orgId),
    supabase.from("leads").select("id", { count: "exact", head: true }).eq("organization_id", orgId).in("status", ["qualified", "appointment", "negotiation"]),
    supabase.from("conversations").select("id", { count: "exact", head: true }).eq("organization_id", orgId).eq("status", "open"),
    supabase.from("deals").select("amount").eq("organization_id", orgId).neq("stage", "lost"),
    supabase.from("leads").select("id, full_name, status, score, source_channel, created_at").eq("organization_id", orgId).order("created_at", { ascending: false }).limit(6),
    supabase.from("appointments").select("id, title, starts_at, status, leads(full_name)").eq("organization_id", orgId).gte("starts_at", new Date().toISOString()).order("starts_at").limit(4),
    supabase.from("follow_ups").select("id", { count: "exact", head: true }).eq("organization_id", orgId).in("status", ["pending", "in_progress"]).lt("due_at", new Date().toISOString()),
  ]);
  const pipelineTotal = (pipeline.data ?? []).reduce((sum, item) => sum + Number(item.amount ?? 0), 0);
  const metrics = [[t.total, leadsCount.count ?? 0, t.month, UsersRound, "blue"],[t.qualified, qualifiedCount.count ?? 0, t.ready, TrendingUp, "green"],[t.overdue, overdueFollowUps.count ?? 0, t.rescue, CalendarClock, "amber"],[t.open, openConversations.count ?? 0, t.reply, MessageCircleMore, "violet"],[t.pipeline, `${Intl.NumberFormat(locale).format(pipelineTotal)} ₺`, t.active, CircleDollarSign, "amber"]] as const;
  return <main className="content"><PageHeader title={t.hello} subtitle={t.sub} action={<Link href="/leads#new" className="primary-button compact"><UserPlus size={17} /> {t.add}</Link>} />
    <section className="metrics-grid">{metrics.map(([label,value,note,Icon,tone])=><article className="metric-card" key={label}><div className={`metric-icon ${tone}`}><Icon size={21}/></div><div><p>{label}</p><strong>{value}</strong><small>{note}</small></div></article>)}</section>
    <section className="dashboard-grid"><article className="panel span-two"><div className="panel-head"><div><h2>{t.recent}</h2><p>{t.priority}</p></div><Link href="/leads">{t.all} <ArrowLeft size={15}/></Link></div><div className="table-wrap"><table><thead><tr><th>{t.customer}</th><th>{t.source}</th><th>{t.status}</th><th>{t.score}</th></tr></thead><tbody>{(recentLeads.data??[]).map(lead=><tr key={lead.id}><td><div className="person"><span>{lead.full_name.slice(0,1)}</span><strong>{lead.full_name}</strong></div></td><td>{lead.source_channel??t.manual}</td><td><span className={`status ${lead.status}`}>{statusLabel(t.statuses,lead.status)}</span></td><td><div className="score"><i style={{width:`${lead.score}%`}}/><b>{lead.score}</b></div></td></tr>)}{!recentLeads.data?.length&&<tr><td colSpan={4}><div className="empty-state"><UsersRound size={28}/><strong>{t.first}</strong><span>{t.journey}</span></div></td></tr>}</tbody></table></div></article>
    <article className="panel"><div className="panel-head"><div><h2>{t.upcoming}</h2><p>{t.timezone}</p></div><CalendarClock size={20}/></div><div className="timeline">{(upcoming.data??[]).map(item=>{const lead=Array.isArray(item.leads)?item.leads[0]:item.leads;return <div className="timeline-item" key={item.id}><time>{new Intl.DateTimeFormat(locale,{hour:"2-digit",minute:"2-digit",timeZone:"Europe/Istanbul"}).format(new Date(item.starts_at))}</time><div><strong>{item.title}</strong><span>{lead?.full_name??t.client}</span></div></div>})}{!upcoming.data?.length&&<div className="empty-mini"><CalendarClock size={25}/><span>{t.none}</span></div>}</div><Link href="/appointments" className="secondary-button">{t.calendar}</Link></article></section>
  </main>;
}
