import Link from "next/link";
import { ArrowLeft, CalendarClock, CircleDollarSign, Flame, MessageCircleMore, TrendingUp, UserPlus, UsersRound } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { getLocale, type Locale } from "@/lib/i18n";
import { requireWorkspace } from "@/lib/workspace";

type StatusKey = "new" | "contacted" | "qualified" | "appointment" | "negotiation" | "won" | "lost" | "disqualified";
type DashboardCopy = {
  hello:string; sub:string; add:string; total:string; month:string; qualified:string; ready:string; overdue:string; rescue:string; open:string; reply:string; pipeline:string; active:string; recent:string; priority:string; all:string; customer:string; source:string; status:string; score:string; manual:string; first:string; journey:string; upcoming:string; timezone:string; client:string; none:string; calendar:string;
  today:string; todaySub:string; noWork:string; noWorkSub:string; overdueAction:string; appointmentAction:string; hotLeadAction:string; openFollowUps:string; openAppointments:string; openLead:string; urgent:string; high:string; scheduled:string;
  statuses: Record<StatusKey,string>;
};
const copy: Record<Locale, DashboardCopy> = {
  ar: { hello:"صباح الخير 👋", sub:"هذه صورة فريقك الآن، من أول رسالة حتى إغلاق الصفقة.", add:"عميل جديد", total:"إجمالي العملاء", month:"هذا الشهر", qualified:"عملاء مؤهلون", ready:"جاهزون للمتابعة", overdue:"متابعات متأخرة", rescue:"فرص تحتاج إنقاذ", open:"محادثات مفتوحة", reply:"تحتاج ردًا", pipeline:"قيمة المسار", active:"الصفقات النشطة", recent:"أحدث العملاء", priority:"الأولوية حسب النتيجة وآخر نشاط", all:"عرض الكل", customer:"العميل", source:"المصدر", status:"الحالة", score:"النتيجة", manual:"يدوي", first:"ابدأ بإضافة أول عميل", journey:"ستظهر رحلة المبيعات هنا مباشرة.", upcoming:"المواعيد القادمة", timezone:"بتوقيت إسطنبول", client:"عميل", none:"لا توجد مواعيد قادمة", calendar:"فتح التقويم", today:"العمل الآن", todaySub:"SatışDesk يرتب أهم الإجراءات حتى لا تضيع فرصة بيع.", noWork:"لا توجد إجراءات عاجلة", noWorkSub:"الفريق مسيطر على المتابعات والمواعيد الحالية.", overdueAction:"متابعة متأخرة", appointmentAction:"موعد قريب", hotLeadAction:"عميل ساخن يحتاج متابعة", openFollowUps:"فتح المتابعات", openAppointments:"فتح المواعيد", openLead:"فتح العميل", urgent:"عاجل", high:"أولوية عالية", scheduled:"مجدول", statuses:{new:"جديد",contacted:"تم التواصل",qualified:"مؤهل",appointment:"موعد",negotiation:"تفاوض",won:"مغلق بنجاح",lost:"مفقود",disqualified:"غير مؤهل"}},
  tr: { hello:"Günaydın 👋", sub:"Ekibinizin ilk mesajdan anlaşmanın kapanışına kadar güncel görünümü.", add:"Yeni müşteri", total:"Toplam müşteri", month:"Bu ay", qualified:"Nitelikli müşteriler", ready:"Takibe hazır", overdue:"Geciken takipler", rescue:"Kurtarılması gereken fırsatlar", open:"Açık konuşmalar", reply:"Yanıt bekliyor", pipeline:"Pipeline değeri", active:"Aktif fırsatlar", recent:"Son müşteriler", priority:"Skor ve son aktiviteye göre öncelik", all:"Tümünü gör", customer:"Müşteri", source:"Kaynak", status:"Durum", score:"Skor", manual:"Manuel", first:"İlk müşterinizi ekleyin", journey:"Satış yolculuğu burada görünecek.", upcoming:"Yaklaşan randevular", timezone:"İstanbul saati", client:"Müşteri", none:"Yaklaşan randevu yok", calendar:"Takvimi aç", today:"Şimdi yapılacaklar", todaySub:"SatışDesk fırsat kaybını önlemek için en önemli işleri öne çıkarır.", noWork:"Acil işlem yok", noWorkSub:"Ekip mevcut takip ve randevuları kontrol altında tutuyor.", overdueAction:"Gecikmiş takip", appointmentAction:"Yaklaşan randevu", hotLeadAction:"Sıcak müşteri takip bekliyor", openFollowUps:"Takipleri aç", openAppointments:"Randevuları aç", openLead:"Müşteriyi aç", urgent:"Acil", high:"Yüksek öncelik", scheduled:"Planlandı", statuses:{new:"Yeni",contacted:"İletişim kuruldu",qualified:"Nitelikli",appointment:"Randevu",negotiation:"Görüşme",won:"Kazanıldı",lost:"Kaybedildi",disqualified:"Uygun değil"}},
  en: { hello:"Good morning 👋", sub:"Your team's live view from first message to closed deal.", add:"New lead", total:"Total leads", month:"This month", qualified:"Qualified leads", ready:"Ready for follow-up", overdue:"Overdue follow-ups", rescue:"Opportunities to rescue", open:"Open conversations", reply:"Need a reply", pipeline:"Pipeline value", active:"Active deals", recent:"Recent leads", priority:"Prioritized by score and recent activity", all:"View all", customer:"Customer", source:"Source", status:"Status", score:"Score", manual:"Manual", first:"Add your first lead", journey:"The sales journey will appear here.", upcoming:"Upcoming appointments", timezone:"Istanbul time", client:"Customer", none:"No upcoming appointments", calendar:"Open calendar", today:"Work now", todaySub:"SatışDesk surfaces the highest-value actions so opportunities do not get lost.", noWork:"No urgent actions", noWorkSub:"The team is on top of current follow-ups and appointments.", overdueAction:"Overdue follow-up", appointmentAction:"Upcoming appointment", hotLeadAction:"Hot lead needs attention", openFollowUps:"Open follow-ups", openAppointments:"Open appointments", openLead:"Open lead", urgent:"Urgent", high:"High priority", scheduled:"Scheduled", statuses:{new:"New",contacted:"Contacted",qualified:"Qualified",appointment:"Appointment",negotiation:"Negotiation",won:"Won",lost:"Lost",disqualified:"Disqualified"}},
};
const statusLabel=(statuses:DashboardCopy["statuses"], status:string)=>status in statuses ? statuses[status as StatusKey] : status;
export default async function DashboardPage() {
  const [{ supabase, organizationId: orgId }, locale] = await Promise.all([requireWorkspace(), getLocale()]);
  const t = copy[locale]; const now = new Date(); const nowIso=now.toISOString(); const soonIso=new Date(now.getTime()+24*60*60*1000).toISOString();
  const [leadsCount, qualifiedCount, openConversations, pipeline, recentLeads, upcoming, overdueFollowUps, overdueItems, hotLeads] = await Promise.all([
    supabase.from("leads").select("id", { count: "exact", head: true }).eq("organization_id", orgId),
    supabase.from("leads").select("id", { count: "exact", head: true }).eq("organization_id", orgId).in("status", ["qualified", "appointment", "negotiation"]),
    supabase.from("conversations").select("id", { count: "exact", head: true }).eq("organization_id", orgId).eq("status", "open"),
    supabase.from("deals").select("amount").eq("organization_id", orgId).neq("stage", "lost"),
    supabase.from("leads").select("id, full_name, status, score, source_channel, created_at").eq("organization_id", orgId).order("created_at", { ascending: false }).limit(6),
    supabase.from("appointments").select("id, title, starts_at, status, leads(full_name)").eq("organization_id", orgId).gte("starts_at", nowIso).order("starts_at").limit(4),
    supabase.from("follow_ups").select("id", { count: "exact", head: true }).eq("organization_id", orgId).in("status", ["pending", "in_progress"]).lt("due_at", nowIso),
    supabase.from("follow_ups").select("id,subject,due_at,leads(full_name)").eq("organization_id",orgId).in("status",["pending","in_progress"]).lt("due_at",nowIso).order("due_at").limit(4),
    supabase.from("leads").select("id,full_name,score,status,created_at").eq("organization_id",orgId).in("status",["new","contacted","qualified"]).gte("score",70).order("score",{ascending:false}).limit(3),
  ]);
  const pipelineTotal = (pipeline.data ?? []).reduce((sum, item) => sum + Number(item.amount ?? 0), 0);
  const metrics = [[t.total, leadsCount.count ?? 0, t.month, UsersRound, "blue"],[t.qualified, qualifiedCount.count ?? 0, t.ready, TrendingUp, "green"],[t.overdue, overdueFollowUps.count ?? 0, t.rescue, CalendarClock, "amber"],[t.open, openConversations.count ?? 0, t.reply, MessageCircleMore, "violet"],[t.pipeline, `${Intl.NumberFormat(locale).format(pipelineTotal)} ₺`, t.active, CircleDollarSign, "amber"]] as const;
  const work=[
    ...(overdueItems.data??[]).map(item=>{const lead=Array.isArray(item.leads)?item.leads[0]:item.leads;return {id:`f-${item.id}`,rank:0,title:item.subject||t.overdueAction,detail:lead?.full_name??t.client,badge:t.urgent,href:"/follow-ups",cta:t.openFollowUps,time:item.due_at};}),
    ...(upcoming.data??[]).filter(item=>item.starts_at<=soonIso).map(item=>{const lead=Array.isArray(item.leads)?item.leads[0]:item.leads;return {id:`a-${item.id}`,rank:1,title:item.title||t.appointmentAction,detail:lead?.full_name??t.client,badge:t.scheduled,href:"/appointments",cta:t.openAppointments,time:item.starts_at};}),
    ...(hotLeads.data??[]).map(item=>({id:`l-${item.id}`,rank:2,title:t.hotLeadAction,detail:`${item.full_name} · ${item.score}`,badge:t.high,href:`/leads?lead=${item.id}`,cta:t.openLead,time:item.created_at})),
  ].sort((a,b)=>a.rank-b.rank||new Date(a.time).getTime()-new Date(b.time).getTime()).slice(0,8);
  return <main className="content"><PageHeader title={t.hello} subtitle={t.sub} action={<Link href="/leads#new" className="primary-button compact"><UserPlus size={17} /> {t.add}</Link>} />
    <section className="metrics-grid">{metrics.map(([label,value,note,Icon,tone])=><article className="metric-card" key={label}><div className={`metric-icon ${tone}`}><Icon size={21}/></div><div><p>{label}</p><strong>{value}</strong><small>{note}</small></div></article>)}</section>
    <section className="panel"><div className="panel-head"><div><h2>{t.today}</h2><p>{t.todaySub}</p></div><Flame size={20}/></div><div className="cards-list">{work.map(item=><div className="task-row" key={item.id}><span className={`task-dot ${item.rank===0?"overdue":"pending"}`}/><div><strong>{item.title}</strong><small>{item.detail} · {item.badge}</small></div><time>{new Intl.DateTimeFormat(locale,{dateStyle:"medium",timeStyle:"short",timeZone:"Europe/Istanbul"}).format(new Date(item.time))}</time><Link className="mini-action" href={item.href}>{item.cta}</Link></div>)}{!work.length&&<div className="empty-state"><TrendingUp size={30}/><strong>{t.noWork}</strong><span>{t.noWorkSub}</span></div>}</div></section>
    <section className="dashboard-grid"><article className="panel span-two"><div className="panel-head"><div><h2>{t.recent}</h2><p>{t.priority}</p></div><Link href="/leads">{t.all} <ArrowLeft size={15}/></Link></div><div className="table-wrap"><table><thead><tr><th>{t.customer}</th><th>{t.source}</th><th>{t.status}</th><th>{t.score}</th></tr></thead><tbody>{(recentLeads.data??[]).map(lead=><tr key={lead.id}><td><div className="person"><span>{lead.full_name.slice(0,1)}</span><strong>{lead.full_name}</strong></div></td><td>{lead.source_channel??t.manual}</td><td><span className={`status ${lead.status}`}>{statusLabel(t.statuses,lead.status)}</span></td><td><div className="score"><i style={{width:`${lead.score}%`}}/><b>{lead.score}</b></div></td></tr>)}{!recentLeads.data?.length&&<tr><td colSpan={4}><div className="empty-state"><UsersRound size={28}/><strong>{t.first}</strong><span>{t.journey}</span></div></td></tr>}</tbody></table></div></article>
    <article className="panel"><div className="panel-head"><div><h2>{t.upcoming}</h2><p>{t.timezone}</p></div><CalendarClock size={20}/></div><div className="timeline">{(upcoming.data??[]).map(item=>{const lead=Array.isArray(item.leads)?item.leads[0]:item.leads;return <div className="timeline-item" key={item.id}><time>{new Intl.DateTimeFormat(locale,{hour:"2-digit",minute:"2-digit",timeZone:"Europe/Istanbul"}).format(new Date(item.starts_at))}</time><div><strong>{item.title}</strong><span>{lead?.full_name??t.client}</span></div></div>})}{!upcoming.data?.length&&<div className="empty-mini"><CalendarClock size={25}/><span>{t.none}</span></div>}</div><Link href="/appointments" className="secondary-button">{t.calendar}</Link></article></section>
  </main>;
}
