begin;
select plan(15);
select has_table('public','quotes','quotes table exists');
select has_table('public','quote_items','quote_items table exists');
select ok((select relrowsecurity from pg_class where oid='public.quotes'::regclass),'quotes RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.quote_items'::regclass),'quote_items RLS enabled');
select has_column('public','quotes','deal_id','quotes link to deals');
select has_column('public','quotes','quote_number','quotes have business identifier');
select has_column('public','quotes','status','quotes have lifecycle status');
select has_column('public','quotes','total','quotes persist commercial total');
select has_column('public','quote_items','quantity','quote items have quantity');
select has_column('public','quote_items','unit_price','quote items have unit price');
select has_column('public','quote_items','discount_rate','quote items support discounts');
select has_column('public','quote_items','tax_rate','quote items support tax');
select has_column('public','quote_items','line_total','quote items calculate line total');
select ok(has_table_privilege('authenticated','public.quotes','SELECT'),'authenticated can reach quotes through Data API grants');
select ok(not has_table_privilege('anon','public.quotes','SELECT'),'anonymous role cannot read quotes');
select * from finish();
rollback;
