import { Plus, UserRoundSearch } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { getLocale, type Locale } from "@/lib/i18n";
import { requireWorkspace } from "@/lib/workspace";
import { createLead } from "../actions";

type StatusKey="new"|"contacted"|"qualified"|"appointment"|"negotiation"|"won"|"lost"|"disqualified";
type LeadsCopy={title:string;sub:string;add:string;hint:string;name:string;full:string;phone:string;email:string;source:string;manual:string;web:string;referral:string;save:string;list:string;record:string;noContact:string;empty:string;emptyHint:string;statuses:Record<StatusKey,string>};
const copy: Record<Locale, LeadsCopy> = {
 ar:{title:"العملاء",sub:"كل فرصة بيع مع مصدرها، حالتها والنتيجة الحالية.",add:"إضافة عميل",hint:"سجل سريع، وكمل التفاصيل لاحقًا",name:"اسم العميل",full:"الاسم الكامل",phone:"رقم الهاتف",email:"البريد الإلكتروني",source:"المصدر",manual:"إدخال يدوي",web:"الموقع",referral:"إحالة",save:"حفظ العميل",list:"قائمة العملاء",record:"سجل",noContact:"بدون معلومات اتصال",empty:"القائمة فارغة",emptyHint:"أضف أول عميل من النموذج.",statuses:{new:"جديد",contacted:"تم التواصل",qualified:"مؤهل",appointment:"موعد",negotiation:"تفاوض",won:"مغلق بنجاح",lost:"مفقود",disqualified:"غير مؤهل"}},
 tr:{title:"Müşteriler",sub:"Her satış fırsatını kaynağı, durumu ve güncel skoruyla yönetin.",add:"Müşteri ekle",hint:"Hızlı kaydedin, ayrıntıları sonra tamamlayın",name:"Müşteri adı",full:"Ad soyad",phone:"Telefon",email:"E-posta",source:"Kaynak",manual:"Manuel giriş",web:"Web sitesi",referral:"Referans",save:"Müşteriyi kaydet",list:"Müşteri listesi",record:"kayıt",noContact:"İletişim bilgisi yok",empty:"Liste boş",emptyHint:"Formdan ilk müşterinizi ekleyin.",statuses:{new:"Yeni",contacted:"İletişim kuruldu",qualified:"Nitelikli",appointment:"Randevu",negotiation:"Görüşme",won:"Kazanıldı",lost:"Kaybedildi",disqualified:"Uygun değil"}},
 en:{title:"Leads",sub:"Manage every sales opportunity with its source, status, and current score.",add:"Add lead",hint:"Create a quick record and complete details later",name:"Customer name",full:"Full name",phone:"Phone",email:"Email",source:"Source",manual:"Manual entry",web:"Website",referral:"Referral",save:"Save lead",list:"Lead list",record:"records",noContact:"No contact information",empty:"The list is empty",emptyHint:"Add your first lead using the form.",statuses:{new:"New",contacted:"Contacted",qualified:"Qualified",appointment:"Appointment",negotiation:"Negotiation",won:"Won",lost:"Lost",disqualified:"Disqualified"}}
};
const statusLabel=(statuses:LeadsCopy["statuses"],status:string)=>status in statuses?statuses[status as StatusKey]:status;
type Props={searchParams:Promise<{error?:string;success?:string}>};
export default async function LeadsPage({searchParams}:Props){
 const [params,locale,{supabase,organizationId}]=await Promise.all([searchParams,getLocale(),requireWorkspace()]); const t=copy[locale];
 const {data:leads}=await supabase.from("leads").select("id, full_name, email, phone, status, score, source_channel, created_at").eq("organization_id",organizationId).order("created_at",{ascending:false});
 return <main className="content"><PageHeader title={t.title} subtitle={t.sub}/>{params.error&&<div className="alert error">{params.error}</div>}{params.success&&<div className="alert success">{params.success}</div>}
 <section className="split-view"><article id="new" className="panel form-panel"><div className="panel-head"><div><h2>{t.add}</h2><p>{t.hint}</p></div><Plus size={20}/></div><form className="stack-form" action={createLead}><label>{t.name}<input name="fullName" required placeholder={t.full}/></label><label>{t.phone}<input name="phone" dir="ltr" placeholder="+90 ..."/></label><label>{t.email}<input name="email" type="email" dir="ltr" placeholder="name@example.com"/></label><label>{t.source}<select name="sourceChannel" defaultValue="manual"><option value="manual">{t.manual}</option><option value="whatsapp">WhatsApp</option><option value="web">{t.web}</option><option value="instagram">Instagram</option><option value="facebook">Facebook</option><option value="referral">{t.referral}</option></select></label><button className="primary-button" type="submit">{t.save}</button></form></article>
 <article className="panel grow"><div className="panel-head"><div><h2>{t.list}</h2><p>{leads?.length??0} {t.record}</p></div><UserRoundSearch size={20}/></div><div className="cards-list">{(leads??[]).map(lead=><div className="lead-row" key={lead.id}><div className="person"><span>{lead.full_name.slice(0,1)}</span><div><strong>{lead.full_name}</strong><small>{lead.phone||lead.email||t.noContact}</small></div></div><div className="lead-meta"><span className={`status ${lead.status}`}>{statusLabel(t.statuses,lead.status)}</span><b>{lead.score}/100</b></div></div>)}{!leads?.length&&<div className="empty-state"><UserRoundSearch size={30}/><strong>{t.empty}</strong><span>{t.emptyHint}</span></div>}</div></article></section></main>;
}
