import { Bot, PlayCircle, ShieldCheck, UserRoundCheck } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { getLocale, type Locale } from "@/lib/i18n";
import { requireWorkspace } from "@/lib/workspace";
import { handoffConversationToHuman, resumeAiConversation } from "./ai-actions";

type Copy={title:string;sub:string;ready:string;isolated:string;rules:string;count:(n:number)=>string;actions:(n:number)=>string;core:string;empty:string;governance:string;governanceHint:string;human:string;ai:string;reason:string;handoff:string;resume:string;none:string};
const copy:Record<Locale,Copy>={
 ar:{title:"الأتمتة",sub:"قواعد قابلة للتتبع مع منع التكرار وسجل تشغيل واضح.",ready:"جاهز لاستقبال قواعد التشغيل",isolated:"كل تشغيل معزول حسب المؤسسة",rules:"قواعد التشغيل",count:n=>`${n} قاعدة`,actions:n=>`${n} إجراء`,core:"الكور جاهز",empty:"أضف أول قاعدة عند ربط قناة الرسائل.",governance:"حوكمة وكيل المبيعات AI",governanceHint:"التحويل للبشر متاح للفريق، وإعادة الاستقلالية للـAI تتطلب صلاحية إدارية.",human:"بشري",ai:"AI",reason:"سبب التحويل",handoff:"تحويل لموظف",resume:"إعادة AI",none:"لا توجد محادثات نشطة"},
 tr:{title:"Otomasyon",sub:"Tekrarı önleyen, izlenebilir kurallar ve açık çalışma kayıtları.",ready:"Otomasyon kurallarını almaya hazır",isolated:"Her çalışma şirket bazında izole edilir",rules:"Otomasyon kuralları",count:n=>`${n} kural`,actions:n=>`${n} işlem`,core:"Çekirdek hazır",empty:"Mesaj kanalı bağlandığında ilk kuralı ekleyin.",governance:"AI satış temsilcisi yönetişimi",governanceHint:"Ekip insan devri yapabilir; AI özerkliğini yeniden açmak yönetici yetkisi gerektirir.",human:"İnsan",ai:"AI",reason:"Devir nedeni",handoff:"İnsana devret",resume:"AI'ı sürdür",none:"Aktif konuşma yok"},
 en:{title:"Automation",sub:"Traceable rules with duplicate prevention and a clear execution log.",ready:"Ready for automation rules",isolated:"Every run is isolated by organization",rules:"Automation rules",count:n=>`${n} rule${n===1?"":"s"}`,actions:n=>`${n} action${n===1?"":"s"}`,core:"Core is ready",empty:"Add the first rule when a messaging channel is connected.",governance:"AI sales agent governance",governanceHint:"Staff can hand off to a human; restoring AI autonomy requires manager authority.",human:"Human",ai:"AI",reason:"Handoff reason",handoff:"Hand off",resume:"Resume AI",none:"No active conversations"}
};
type Props={searchParams:Promise<{error?:string;success?:string}>};
export default async function AutomationPage({searchParams}:Props){
 const [params,locale,{supabase,organizationId}]=await Promise.all([searchParams,getLocale(),requireWorkspace()]);const t=copy[locale];
 const [{data:rules},{data:conversations}]=await Promise.all([
  supabase.from("automation_rules").select("id,name,trigger_type,is_active,last_run_at,actions").eq("organization_id",organizationId).order("created_at"),
  supabase.from("conversations").select("id,handling_mode,handoff_reason,summary,last_message_at,leads(full_name)").eq("organization_id",organizationId).in("handling_mode",["ai","human"]).order("last_message_at",{ascending:false,nullsFirst:false}).limit(20)
 ]);
 return <main className="content"><PageHeader title={t.title} subtitle={t.sub}/>{params.error&&<div className="alert error">{params.error}</div>}{params.success&&<div className="alert success">{params.success}</div>}<section className="automation-intro"><div><Bot size={26}/><span><strong>Automation Core</strong><small>{t.ready}</small></span></div><div><ShieldCheck size={18}/> {t.isolated}</div></section>
 <section className="panel"><div className="panel-head"><div><h2>{t.governance}</h2><p>{t.governanceHint}</p></div><UserRoundCheck size={20}/></div><div className="cards-list">{(conversations??[]).map(item=>{const lead=Array.isArray(item.leads)?item.leads[0]:item.leads;return <div className="rule-row" key={item.id}><span className={`toggle ${item.handling_mode==="ai"?"on":""}`}/><div><strong>{lead?.full_name??item.summary??item.id.slice(0,8)}</strong><small>{item.handling_mode==="human"?`${t.human}${item.handoff_reason?` · ${item.handoff_reason}`:""}`:t.ai}</small></div>{item.handling_mode==="human"?<form action={resumeAiConversation}><input type="hidden" name="conversationId" value={item.id}/><button className="secondary-button compact" type="submit">{t.resume}</button></form>:<form action={handoffConversationToHuman} className="reply-form"><input type="hidden" name="conversationId" value={item.id}/><input name="reason" minLength={3} maxLength={500} placeholder={t.reason} required/><button className="secondary-button compact" type="submit">{t.handoff}</button></form>}</div>})}{!conversations?.length&&<div className="empty-state"><Bot size={30}/><span>{t.none}</span></div>}</div></section>
 <section className="panel"><div className="panel-head"><div><h2>{t.rules}</h2><p>{t.count(rules?.length??0)}</p></div><PlayCircle size={20}/></div><div className="cards-list">{(rules??[]).map(rule=><div className="rule-row" key={rule.id}><span className={`toggle ${rule.is_active?"on":""}`}/><div><strong>{rule.name}</strong><small>{rule.trigger_type}</small></div><span>{t.actions(Array.isArray(rule.actions)?rule.actions.length:0)}</span></div>)}{!rules?.length&&<div className="empty-state"><Bot size={30}/><strong>{t.core}</strong><span>{t.empty}</span></div>}</div></section></main>;
}
