import { CalendarDays, Clock3, Plus } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { getLocale, type Locale } from "@/lib/i18n";
import { requireWorkspace } from "@/lib/workspace";
import { createAppointment, updateAppointmentStatus } from "../actions";

type Status="scheduled"|"confirmed"|"completed"|"cancelled"|"no_show";
const nextStatuses:Record<Status,Status[]>={scheduled:["confirmed","cancelled"],confirmed:["completed","cancelled","no_show"],completed:[],cancelled:[],no_show:[]};
type Copy={title:string;sub:string;new:string;timezone:string;customer:string;choose:string;appointmentTitle:string;titlePlaceholder:string;start:string;duration:string;min30:string;hour:string;min90:string;hours2:string;location:string;locationPlaceholder:string;save:string;schedule:string;client:string;remote:string;next:string;cancelReason:string;update:string;empty:string;emptyHint:string;statuses:Record<Status,string>};
const copy:Record<Locale,Copy>={
 ar:{title:"المواعيد",sub:"جدول المعاينات والاجتماعات مع حالة تشغيلية واضحة حتى الإغلاق.",new:"موعد جديد",timezone:"التوقيت: إسطنبول",customer:"العميل",choose:"اختر العميل",appointmentTitle:"عنوان الموعد",titlePlaceholder:"معاينة عقار",start:"وقت البداية",duration:"المدة",min30:"30 دقيقة",hour:"ساعة",min90:"90 دقيقة",hours2:"ساعتان",location:"المكان",locationPlaceholder:"المكتب أو عنوان العقار",save:"حفظ الموعد",schedule:"الجدول",client:"عميل",remote:"عن بُعد",next:"الحالة التالية",cancelReason:"سبب الإلغاء مطلوب عند الإلغاء",update:"تحديث",empty:"لا توجد مواعيد",emptyHint:"اختر عميلًا وأضف أول موعد.",statuses:{scheduled:"مجدول",confirmed:"مؤكد",completed:"مكتمل",cancelled:"ملغي",no_show:"لم يحضر"}},
 tr:{title:"Randevular",sub:"Görüşme ve toplantıları kapanışa kadar net operasyon durumlarıyla yönetin.",new:"Yeni randevu",timezone:"Saat dilimi: İstanbul",customer:"Müşteri",choose:"Müşteri seçin",appointmentTitle:"Randevu başlığı",titlePlaceholder:"Mülk gösterimi",start:"Başlangıç",duration:"Süre",min30:"30 dakika",hour:"1 saat",min90:"90 dakika",hours2:"2 saat",location:"Konum",locationPlaceholder:"Ofis veya adres",save:"Randevuyu kaydet",schedule:"Takvim",client:"Müşteri",remote:"Uzaktan",next:"Sonraki durum",cancelReason:"İptal durumunda neden zorunludur",update:"Güncelle",empty:"Randevu yok",emptyHint:"Bir müşteri seçip ilk randevuyu ekleyin.",statuses:{scheduled:"Planlandı",confirmed:"Onaylandı",completed:"Tamamlandı",cancelled:"İptal edildi",no_show:"Gelmedi"}},
 en:{title:"Appointments",sub:"Manage meetings and visits with clear operational status through closure.",new:"New appointment",timezone:"Timezone: Istanbul",customer:"Customer",choose:"Choose customer",appointmentTitle:"Appointment title",titlePlaceholder:"Property viewing",start:"Start time",duration:"Duration",min30:"30 minutes",hour:"1 hour",min90:"90 minutes",hours2:"2 hours",location:"Location",locationPlaceholder:"Office or address",save:"Save appointment",schedule:"Schedule",client:"Customer",remote:"Remote",next:"Next status",cancelReason:"Cancellation reason is required when cancelling",update:"Update",empty:"No appointments",emptyHint:"Choose a customer and add the first appointment.",statuses:{scheduled:"Scheduled",confirmed:"Confirmed",completed:"Completed",cancelled:"Cancelled",no_show:"No show"}}
};
const localeCode:Record<Locale,string>={ar:"ar",tr:"tr-TR",en:"en-US"};
type Props={searchParams:Promise<{error?:string;success?:string}>};
export default async function AppointmentsPage({searchParams}:Props){
 const [params,locale,{supabase,organizationId}]=await Promise.all([searchParams,getLocale(),requireWorkspace()]);const t=copy[locale];const [appointments,leads]=await Promise.all([supabase.from("appointments").select("id,title,starts_at,ends_at,status,location,cancellation_reason,leads(full_name)").eq("organization_id",organizationId).order("starts_at"),supabase.from("leads").select("id,full_name").eq("organization_id",organizationId).order("full_name")]);
 return <main className="content"><PageHeader title={t.title} subtitle={t.sub}/>{params.error&&<div className="alert error">{params.error}</div>}{params.success&&<div className="alert success">{params.success}</div>}<section className="split-view"><article className="panel form-panel"><div className="panel-head"><div><h2>{t.new}</h2><p>{t.timezone}</p></div><Plus size={20}/></div><form className="stack-form" action={createAppointment}><label>{t.customer}<select name="leadId" required defaultValue=""><option value="" disabled>{t.choose}</option>{(leads.data??[]).map(lead=><option key={lead.id} value={lead.id}>{lead.full_name}</option>)}</select></label><label>{t.appointmentTitle}<input name="title" required placeholder={t.titlePlaceholder}/></label><label>{t.start}<input name="startsAt" type="datetime-local" required/></label><label>{t.duration}<select name="durationMinutes" defaultValue="60"><option value="30">{t.min30}</option><option value="60">{t.hour}</option><option value="90">{t.min90}</option><option value="120">{t.hours2}</option></select></label><label>{t.location}<input name="location" placeholder={t.locationPlaceholder}/></label><button className="primary-button" type="submit" disabled={!leads.data?.length}>{t.save}</button></form></article>
 <article className="panel grow"><div className="panel-head"><div><h2>{t.schedule}</h2><p>Europe / Istanbul</p></div><CalendarDays size={20}/></div><div className="appointment-list">{(appointments.data??[]).map(item=>{const lead=Array.isArray(item.leads)?item.leads[0]:item.leads;const date=new Date(item.starts_at);const status=(item.status in nextStatuses?item.status:"scheduled") as Status;const availableStatuses=nextStatuses[status];return <div className="appointment-row" key={item.id}><div className="date-tile"><b>{new Intl.DateTimeFormat(localeCode[locale],{day:"numeric",timeZone:"Europe/Istanbul"}).format(date)}</b><span>{new Intl.DateTimeFormat(localeCode[locale],{month:"short",timeZone:"Europe/Istanbul"}).format(date)}</span></div><div><strong>{item.title}</strong><span>{lead?.full_name??t.client} · {item.location??t.remote} · {t.statuses[status]}</span>{item.cancellation_reason&&<small>{item.cancellation_reason}</small>}{availableStatuses.length>0&&<form className="stack-form" action={updateAppointmentStatus}><input type="hidden" name="appointmentId" value={item.id}/><select name="status" required defaultValue=""><option value="" disabled>{t.next}</option>{availableStatuses.map(next=><option key={next} value={next}>{t.statuses[next]}</option>)}</select><input name="cancellationReason" maxLength={500} placeholder={t.cancelReason}/><button className="mini-action" type="submit">{t.update}</button></form>}</div><time><Clock3 size={15}/> {new Intl.DateTimeFormat(localeCode[locale],{hour:"2-digit",minute:"2-digit",timeZone:"Europe/Istanbul"}).format(date)}</time></div>})}{!appointments.data?.length&&<div className="empty-state"><CalendarDays size={30}/><strong>{t.empty}</strong><span>{t.emptyHint}</span></div>}</div></article></section></main>;
}
