import "server-only";

import { cookies, headers } from "next/headers";

export const locales = ["ar", "tr", "en"] as const;
export type Locale = (typeof locales)[number];

export function isLocale(value: string | undefined | null): value is Locale {
  return locales.includes(value as Locale);
}

export async function getLocale(): Promise<Locale> {
  const saved = (await cookies()).get("satisdesk_locale")?.value;
  if (isLocale(saved)) return saved;
  const accepted = (await headers()).get("accept-language")?.toLowerCase() ?? "";
  if (accepted.startsWith("tr") || accepted.includes(",tr")) return "tr";
  if (accepted.startsWith("ar") || accepted.includes(",ar")) return "ar";
  return "en";
}

export const localeMeta: Record<Locale, { dir: "rtl" | "ltr"; language: string }> = {
  ar: { dir: "rtl", language: "العربية" }, tr: { dir: "ltr", language: "Türkçe" }, en: { dir: "ltr", language: "English" },
};

export const publicCopy = {
  ar: {
    pilot: "العرض المؤسس", login: "تسجيل الدخول", pricing: "الأسعار", pill: "مركز مبيعات متعدد اللغات للفرق الحديثة", title: "لا تدع فرصة بيع تضيع بين واتساب والدفاتر.", intro: "SatışDesk يجمع العميل والمحادثة والمتابعة والموعد والصفقة في شاشة واحدة، ويعطي فريقك مسارًا عمليًا للرد والإغلاق.", start: "ابدأ الآن", how: "شاهد كيف يعمل", quick: "إعداد سريع", flexible: "بدون عقد طويل", transparent: "رسوم Meta منفصلة وواضحة", why: "لماذا SatışDesk؟", operating: "تشغيل المبيعات كما يجب أن يكون", simple: "بسيط للموظف، واضح للمدير، وآمن للمؤسسة.", outcomes: [["كل المحادثات في مكان واحد", "واتساب والعملاء والمتابعات والصفقات ضمن رحلة واحدة واضحة."],["العربية · Türkçe · English", "فريقك والعميل يتحدثان بلغتهما مع حفظ النص الأصلي والترجمة."],["من الرسالة إلى الصفقة", "اعرف المصدر، سرعة الرد، الموعد وقيمة المسار بدون ملفات متفرقة."],["مساحة معزولة لكل مؤسسة", "أدوار وصلاحيات وعزل بيانات على مستوى قاعدة البيانات."]], pilotTitle: "نجهّز فريقك ونشغّل أول مسار بيع خلال أيام.", pilotText: "يشمل إعداد المؤسسة، استيراد أول العملاء، تدريب الفريق، تصميم مراحل المتابعة، ودعم الإطلاق.", setupMonth: "الإعداد + أول شهر", pilotNote: "حتى 5 مستخدمين · رسوم WhatsApp/Meta حسب الاستهلاك", reserve: "احجز مكانك في الـPilot", teamLogin: "دخول الفريق", authEyebrow: "مركز قيادة المبيعات", authTitle: "حوّل كل محادثة إلى فرصة واضحة.", authIntro: "CRM متعدد اللغات يجمع العملاء، الرسائل، المتابعات والصفقات في مكان واحد—معزول وآمن لكل مؤسسة.", welcome: "أهلًا بعودتك", startOrg: "ابدأ مؤسستك", signIn: "تسجيل الدخول", signUp: "إنشاء حساب جديد", authSignInHint: "ادخل إلى مركز قيادة المبيعات", authSignUpHint: "جهّز مساحة فريقك خلال دقيقة", fullName: "الاسم الكامل", email: "البريد الإلكتروني", password: "كلمة المرور", passwordHint: "10 أحرف على الأقل، بينها حروف وأرقام", secureLogin: "دخول آمن", createAccount: "إنشاء الحساب", hasAccount: "لديك حساب؟ سجّل الدخول", firstTime: "أول مرة؟ أنشئ حساب مؤسستك", pricingTitle: "خطط واضحة تنمو مع فريقك", pricingIntro: "ابدأ بالخطة المناسبة، واحتفظ بسلطة الاشتراك والفوترة على الخادم.", monthly: "شهريًا", yearly: "سنويًا", users: "مستخدمين", custom: "حسب الاتفاق", choose: "ابدأ بهذه الخطة", enterprise: "تواصل معنا", founding: "Founding Pilot: إعداد مُدار + أول شهر مقابل 50,000 ₺.",
  },
  tr: {
    pilot: "Kurucu pilot", login: "Giriş", pricing: "Fiyatlar", pill: "Modern ekipler için çok dilli satış merkezi", title: "WhatsApp ile notlar arasında hiçbir satış fırsatını kaybetmeyin.", intro: "SatışDesk müşteriyi, konuşmayı, takibi, randevuyu ve anlaşmayı tek ekranda birleştirir.", start: "Hemen başlayın", how: "Nasıl çalışır?", quick: "Hızlı kurulum", flexible: "Uzun sözleşme yok", transparent: "Meta ücretleri açık ve ayrı", why: "Neden SatışDesk?", operating: "Satış operasyonunun doğru hali", simple: "Temsilci için kolay, yönetici için net, şirket için güvenli.", outcomes: [["Tüm konuşmalar tek yerde", "WhatsApp, müşteri, takip ve fırsatlar tek bir yolculukta."],["Arapça · Türkçe · English", "Ekip ve müşteri tercih ettiği dilde çalışır."],["Mesajdan gelire", "Kaynağı, yanıtı, randevuyu ve değeri görün."],["Her şirket için izole alan", "Veritabanı seviyesinde roller ve tenant izolasyonu."]], pilotTitle: "Ekibinizi kurup ilk satış akışını günler içinde çalıştırıyoruz.", pilotText: "Şirket kurulumu, ilk müşteri aktarımı, ekip eğitimi ve lansman desteği dahildir.", setupMonth: "Kurulum + ilk ay", pilotNote: "5 kullanıcıya kadar · WhatsApp/Meta kullanımı ayrıca", reserve: "Pilot yerinizi ayırın", teamLogin: "Ekip girişi", authEyebrow: "Satış komuta merkezi", authTitle: "Her konuşmayı görünür bir fırsata dönüştürün.", authIntro: "Müşterileri, mesajları, takipleri ve fırsatları güvenli bir alanda birleştiren çok dilli CRM.", welcome: "Tekrar hoş geldiniz", startOrg: "Şirketinizi başlatın", signIn: "Giriş yap", signUp: "Yeni hesap oluştur", authSignInHint: "Satış merkezinize girin", authSignUpHint: "Çalışma alanınızı bir dakikada kurun", fullName: "Ad soyad", email: "E-posta", password: "Şifre", passwordHint: "En az 10 karakter, harf ve rakam içermeli", secureLogin: "Güvenli giriş", createAccount: "Hesap oluştur", hasAccount: "Hesabınız var mı? Giriş yapın", firstTime: "İlk kez mi? Şirket hesabı oluşturun", pricingTitle: "Ekibinizle büyüyen net planlar", pricingIntro: "Size uygun planla başlayın; abonelik ve yetkiler sunucu tarafından yönetilsin.", monthly: "aylık", yearly: "yıllık", users: "kullanıcı", custom: "Özel", choose: "Bu planla başlayın", enterprise: "Bize ulaşın", founding: "Founding Pilot: Yönetilen kurulum + ilk ay 50.000 ₺.",
  },
  en: {
    pilot: "Founding pilot", login: "Sign in", pricing: "Pricing", pill: "A multilingual sales hub for modern teams", title: "Stop losing sales opportunities between WhatsApp and spreadsheets.", intro: "SatışDesk brings customers, conversations, follow-ups, appointments, and deals into one operational view.", start: "Get started", how: "See how it works", quick: "Fast setup", flexible: "No long contract", transparent: "Transparent Meta usage fees", why: "Why SatışDesk?", operating: "Sales operations as they should be", simple: "Simple for agents, clear for managers, secure for the company.", outcomes: [["Every conversation in one place", "WhatsApp, leads, follow-ups, and deals in one clear journey."],["Arabic · Türkçe · English", "Your team and customers work in their preferred language."],["From message to revenue", "See source, response, appointment, and pipeline value."],["An isolated workspace per company", "Roles and tenant isolation enforced at database level."]], pilotTitle: "We set up your team and launch the first sales flow in days.", pilotText: "Includes workspace setup, first lead import, team training, workflow design, and launch support.", setupMonth: "Setup + first month", pilotNote: "Up to 5 users · WhatsApp/Meta usage billed separately", reserve: "Reserve your pilot place", teamLogin: "Team sign in", authEyebrow: "Sales command center", authTitle: "Turn every conversation into a visible opportunity.", authIntro: "A multilingual CRM that brings leads, messages, follow-ups, and deals into one secure workspace.", welcome: "Welcome back", startOrg: "Start your company", signIn: "Sign in", signUp: "Create a new account", authSignInHint: "Enter your sales command center", authSignUpHint: "Set up your workspace in a minute", fullName: "Full name", email: "Email", password: "Password", passwordHint: "At least 10 characters with letters and numbers", secureLogin: "Secure sign in", createAccount: "Create account", hasAccount: "Already have an account? Sign in", firstTime: "New here? Create your company account", pricingTitle: "Clear plans that grow with your team", pricingIntro: "Start with the right plan while subscription state and entitlements stay server-authoritative.", monthly: "monthly", yearly: "yearly", users: "users", custom: "Custom", choose: "Choose this plan", enterprise: "Contact us", founding: "Founding Pilot: managed setup + first month for 50,000 ₺.",
  },
} as const;
