import { AlarmClockPlus, CheckCircle2 } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { getLocale, type Locale } from "@/lib/i18n";
import { requireWorkspace } from "@/lib/workspace";
import { completeFollowUp, createFollowUp } from "../actions";

type Copy={title:string;sub:string;overdue:(n:number)=>string;overdueHint:string;new:string;link:string;customer:string;choose:string;subject:string;placeholder:string;due:string;schedule:string;work:string;open:(n:number)=>string;customerFallback:string;late:string;done:string;allDone:string;none:string};
const copy:Record<Locale,Copy>={
 ar:{title:"المتابعات",sub:"لا فرصة تضيع: المهام المتأخرة تظهر أولًا ويمكن إغلاقها فورًا.",overdue:n=>`${n} متابعة متأخرة تحتاج إجراء`,overdueHint:"SatışDesk يضعها أمام الفريق حتى لا تضيع فرصة بيع بسبب النسيان.",new:"متابعة جديدة",link:"اربط المهمة بالعميل",customer:"العميل",choose:"اختر العميل",subject:"الموضوع",placeholder:"اتصال لمراجعة العرض",due:"موعد الاستحقاق",schedule:"جدولة المتابعة",work:"قائمة العمل",open:n=>`${n} مهمة مفتوحة`,customerFallback:"عميل",late:"متأخرة",done:"تم",allDone:"كل شيء منجز",none:"لا توجد متابعات معلّقة."},
 tr:{title:"Takipler",sub:"Hiçbir fırsat kaybolmasın: geciken görevler önce görünür ve hemen kapatılabilir.",overdue:n=>`${n} gecikmiş takip işlem bekliyor`,overdueHint:"SatışDesk unutulan bir görev yüzünden fırsat kaybolmaması için bunları ekibin önünde tutar.",new:"Yeni takip",link:"Görevi müşteriyle ilişkilendirin",customer:"Müşteri",choose:"Müşteri seçin",subject:"Konu",placeholder:"Teklifi gözden geçirmek için arama",due:"Son tarih",schedule:"Takibi planla",work:"İş listesi",open:n=>`${n} açık görev`,customerFallback:"Müşteri",late:"Gecikmiş",done:"Tamamla",allDone:"Her şey tamam",none:"Bekleyen takip yok."},
 en:{title:"Follow-ups",sub:"Keep every opportunity moving: overdue tasks appear first and can be closed immediately.",overdue:n=>`${n} overdue follow-up${n===1?"":"s"} need action`,overdueHint:"SatışDesk keeps them visible so a sales opportunity is not lost to a forgotten task.",new:"New follow-up",link:"Link the task to a customer",customer:"Customer",choose:"Choose customer",subject:"Subject",placeholder:"Call to review the proposal",due:"Due date",schedule:"Schedule follow-up",work:"Work list",open:n=>`${n} open task${n===1?"":"s"}`,customerFallback:"Customer",late:"Overdue",done:"Done",allDone:"Everything is done",none:"No pending follow-ups."}
};
const localeCode:Record<Locale,string>={ar:"ar",tr:"tr-TR",en:"en-US"};
type Props={searchParams:Promise<{error?:string;success?:string}>};
export default async function FollowUpsPage({searchParams}:Props){
 const [params,locale,{supabase,organizationId:orgId}]=await Promise.all([searchParams,getLocale(),requireWorkspace()]); const t=copy[locale]; const now=new Date();
 const [items,leads]=await Promise.all([supabase.from("follow_ups").select("id,subject,due_at,status,follow_up_type,leads(full_name)").eq("organization_id",orgId).in("status",["pending","in_progress"]).order("due_at"),supabase.from("leads").select("id,full_name").eq("organization_id",orgId).order("full_name")]);
 const pending=items.data??[]; const overdueCount=pending.filter(item=>new Date(item.due_at)<now).length;
 return <main className="content"><PageHeader title={t.title} subtitle={t.sub}/>{params.error&&<div className="alert error">{params.error}</div>}{params.success&&<div className="alert success">{params.success}</div>}{overdueCount>0&&<div className="connector-notice"><AlarmClockPlus size={20}/><div><strong>{t.overdue(overdueCount)}</strong><span>{t.overdueHint}</span></div></div>}
 <section className="split-view"><article className="panel form-panel"><div className="panel-head"><div><h2>{t.new}</h2><p>{t.link}</p></div><AlarmClockPlus size={20}/></div><form className="stack-form" action={createFollowUp}><label>{t.customer}<select name="leadId" required defaultValue=""><option value="" disabled>{t.choose}</option>{(leads.data??[]).map(lead=><option key={lead.id} value={lead.id}>{lead.full_name}</option>)}</select></label><label>{t.subject}<input name="subject" required placeholder={t.placeholder}/></label><label>{t.due}<input name="dueAt" type="datetime-local" required/></label><button className="primary-button" type="submit">{t.schedule}</button></form></article>
 <article className="panel grow"><div className="panel-head"><div><h2>{t.work}</h2><p>{t.open(pending.length)}</p></div><CheckCircle2 size={20}/></div><div className="cards-list">{pending.map(item=>{const lead=Array.isArray(item.leads)?item.leads[0]:item.leads;const overdue=new Date(item.due_at)<now;return <div className="task-row" key={item.id}><span className={`task-dot ${overdue?"overdue":item.status}`}/><div><strong>{item.subject||item.follow_up_type}</strong><small>{lead?.full_name??t.customerFallback}{overdue?` · ${t.late}`:""}</small></div><time>{new Intl.DateTimeFormat(localeCode[locale],{dateStyle:"medium",timeStyle:"short",timeZone:"Europe/Istanbul"}).format(new Date(item.due_at))}</time><form action={completeFollowUp}><input type="hidden" name="followUpId" value={item.id}/><button className="mini-action" type="submit">{t.done}</button></form></div>})}{!pending.length&&<div className="empty-state"><CheckCircle2 size={30}/><strong>{t.allDone}</strong><span>{t.none}</span></div>}</div></article></section></main>;
}
