begin;

create table if not exists public.whatsapp_connections (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  phone_number_id text not null,
  whatsapp_business_account_id text,
  display_phone_number text,
  display_name text,
  status text not null default 'pending' check (status in ('pending','active','paused','error')),
  access_token_env_key text,
  metadata jsonb not null default '{}'::jsonb,
  created_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, phone_number_id),
  unique (phone_number_id),
  foreign key (organization_id, created_by) references public.organization_members(organization_id, user_id) on delete set null
);
create index if not exists whatsapp_connections_org_status_idx on public.whatsapp_connections(organization_id, status);

create table if not exists public.marketing_campaigns (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  platform text not null check (platform in ('meta','google','tiktok','linkedin','other')),
  external_campaign_id text,
  name text not null,
  objective text,
  status text not null default 'active' check (status in ('active','paused','ended','unknown')),
  currency text not null default 'TRY' check (currency ~ '^[A-Z]{3}$'),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, id),
  unique (organization_id, platform, external_campaign_id)
);
create index if not exists marketing_campaigns_org_platform_idx on public.marketing_campaigns(organization_id, platform, status);

create table if not exists public.marketing_ads (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  campaign_id uuid not null,
  external_ad_id text,
  external_adset_id text,
  adset_name text,
  name text not null,
  creative_name text,
  destination text,
  status text not null default 'active' check (status in ('active','paused','ended','unknown')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, id),
  unique (organization_id, external_ad_id),
  foreign key (organization_id, campaign_id) references public.marketing_campaigns(organization_id, id) on delete cascade
);
create index if not exists marketing_ads_campaign_idx on public.marketing_ads(organization_id, campaign_id);

create table if not exists public.marketing_daily_metrics (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  campaign_id uuid,
  ad_id uuid,
  metric_date date not null,
  impressions bigint not null default 0 check (impressions >= 0),
  reach bigint not null default 0 check (reach >= 0),
  clicks bigint not null default 0 check (clicks >= 0),
  spend numeric(18,4) not null default 0 check (spend >= 0),
  leads_count integer not null default 0 check (leads_count >= 0),
  qualified_leads_count integer not null default 0 check (qualified_leads_count >= 0),
  appointments_count integer not null default 0 check (appointments_count >= 0),
  won_deals_count integer not null default 0 check (won_deals_count >= 0),
  revenue numeric(18,4) not null default 0 check (revenue >= 0),
  currency text not null default 'TRY' check (currency ~ '^[A-Z]{3}$'),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  foreign key (organization_id, campaign_id) references public.marketing_campaigns(organization_id, id) on delete cascade,
  foreign key (organization_id, ad_id) references public.marketing_ads(organization_id, id) on delete cascade,
  unique (organization_id, metric_date, campaign_id, ad_id)
);
create index if not exists marketing_metrics_org_date_idx on public.marketing_daily_metrics(organization_id, metric_date desc);

create table if not exists public.lead_attributions (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  lead_id uuid not null,
  campaign_id uuid,
  ad_id uuid,
  platform text not null default 'other' check (platform in ('meta','google','tiktok','linkedin','web','whatsapp','referral','manual','other')),
  attribution_model text not null default 'last_touch' check (attribution_model in ('first_touch','last_touch','self_reported','imported')),
  source text,
  medium text,
  campaign_name text,
  ad_name text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_content text,
  click_id text,
  first_touch_at timestamptz,
  last_touch_at timestamptz,
  raw_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, lead_id, attribution_model),
  foreign key (organization_id, lead_id) references public.leads(organization_id, id) on delete cascade,
  foreign key (organization_id, campaign_id) references public.marketing_campaigns(organization_id, id) on delete set null,
  foreign key (organization_id, ad_id) references public.marketing_ads(organization_id, id) on delete set null
);
create index if not exists lead_attributions_org_platform_idx on public.lead_attributions(organization_id, platform, created_at desc);

alter table public.whatsapp_connections enable row level security;
alter table public.marketing_campaigns enable row level security;
alter table public.marketing_ads enable row level security;
alter table public.marketing_daily_metrics enable row level security;
alter table public.lead_attributions enable row level security;

revoke all on table public.whatsapp_connections from anon;
revoke all on table public.marketing_campaigns from anon;
revoke all on table public.marketing_ads from anon;
revoke all on table public.marketing_daily_metrics from anon;
revoke all on table public.lead_attributions from anon;

grant select, insert, update, delete on table public.whatsapp_connections to authenticated;
grant select, insert, update, delete on table public.marketing_campaigns to authenticated;
grant select, insert, update, delete on table public.marketing_ads to authenticated;
grant select, insert, update, delete on table public.marketing_daily_metrics to authenticated;
grant select, insert, update, delete on table public.lead_attributions to authenticated;
grant usage, select on sequence public.marketing_daily_metrics_id_seq to authenticated;

create policy whatsapp_connections_member_select on public.whatsapp_connections for select to authenticated using (private.is_org_member(organization_id));
create policy whatsapp_connections_admin_write on public.whatsapp_connections for all to authenticated using (private.has_org_role(organization_id, array['owner','admin'])) with check (private.has_org_role(organization_id, array['owner','admin']));

create policy marketing_campaigns_member_select on public.marketing_campaigns for select to authenticated using (private.is_org_member(organization_id));
create policy marketing_campaigns_manager_write on public.marketing_campaigns for all to authenticated using (private.has_org_role(organization_id, array['owner','admin','manager'])) with check (private.has_org_role(organization_id, array['owner','admin','manager']));
create policy marketing_ads_member_select on public.marketing_ads for select to authenticated using (private.is_org_member(organization_id));
create policy marketing_ads_manager_write on public.marketing_ads for all to authenticated using (private.has_org_role(organization_id, array['owner','admin','manager'])) with check (private.has_org_role(organization_id, array['owner','admin','manager']));
create policy marketing_metrics_member_select on public.marketing_daily_metrics for select to authenticated using (private.is_org_member(organization_id));
create policy marketing_metrics_manager_write on public.marketing_daily_metrics for all to authenticated using (private.has_org_role(organization_id, array['owner','admin','manager'])) with check (private.has_org_role(organization_id, array['owner','admin','manager']));
create policy lead_attributions_member_select on public.lead_attributions for select to authenticated using (private.is_org_member(organization_id));
create policy lead_attributions_staff_write on public.lead_attributions for all to authenticated using (private.has_org_role(organization_id, array['owner','admin','manager','agent'])) with check (private.has_org_role(organization_id, array['owner','admin','manager','agent']));

commit;
