-- WS10 Professional Quotes & Commercial Documents
create sequence if not exists public.quote_number_seq;
create table if not exists public.quotes (
 id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, deal_id uuid not null references public.deals(id) on delete restrict, lead_id uuid not null references public.leads(id) on delete restrict,
 quote_number text not null default ('Q-'||to_char(now(),'YYYY')||'-'||lpad(nextval('public.quote_number_seq')::text,6,'0')), status text not null default 'draft' check(status in('draft','sent','accepted','rejected','expired')), currency text not null check(currency in('TRY','USD','EUR')), valid_until date, notes text,
 subtotal numeric(14,2) not null default 0 check(subtotal>=0), discount_total numeric(14,2) not null default 0 check(discount_total>=0), tax_total numeric(14,2) not null default 0 check(tax_total>=0), total numeric(14,2) not null default 0 check(total>=0), created_by uuid not null references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), sent_at timestamptz, accepted_at timestamptz, unique(organization_id,quote_number)
);
create table if not exists public.quote_items (
 id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, quote_id uuid not null references public.quotes(id) on delete cascade, sort_order integer not null default 0, description text not null check(char_length(btrim(description)) between 1 and 300), quantity numeric(12,3) not null check(quantity>0), unit_price numeric(14,2) not null check(unit_price>=0), discount_percent numeric(5,2) not null default 0 check(discount_percent between 0 and 100), tax_percent numeric(5,2) not null default 0 check(tax_percent between 0 and 100), line_subtotal numeric(14,2) not null check(line_subtotal>=0), line_discount numeric(14,2) not null check(line_discount>=0), line_tax numeric(14,2) not null check(line_tax>=0), line_total numeric(14,2) not null check(line_total>=0), created_at timestamptz not null default now()
);
create index if not exists quotes_org_deal_idx on public.quotes(organization_id,deal_id,created_at desc);create index if not exists quote_items_org_quote_idx on public.quote_items(organization_id,quote_id,sort_order);
alter table public.quotes enable row level security;alter table public.quote_items enable row level security;revoke all on public.quotes,public.quote_items from anon;revoke all on sequence public.quote_number_seq from anon;grant select,insert,update,delete on public.quotes,public.quote_items to authenticated;grant usage,select on sequence public.quote_number_seq to authenticated;
drop policy if exists quotes_tenant_select on public.quotes;create policy quotes_tenant_select on public.quotes for select to authenticated using((select auth.uid()) is not null and private.is_active_org_user(organization_id,(select auth.uid())));
drop policy if exists quotes_tenant_insert on public.quotes;create policy quotes_tenant_insert on public.quotes for insert to authenticated with check(private.is_active_org_user(organization_id,(select auth.uid())) and created_by=(select auth.uid()) and exists(select 1 from public.deals d where d.id=deal_id and d.organization_id=organization_id and d.lead_id=lead_id) and exists(select 1 from public.leads l where l.id=lead_id and l.organization_id=organization_id));
drop policy if exists quotes_tenant_update on public.quotes;create policy quotes_tenant_update on public.quotes for update to authenticated using(private.is_active_org_user(organization_id,(select auth.uid()))) with check(private.is_active_org_user(organization_id,(select auth.uid())) and exists(select 1 from public.deals d where d.id=deal_id and d.organization_id=organization_id and d.lead_id=lead_id) and exists(select 1 from public.leads l where l.id=lead_id and l.organization_id=organization_id));
drop policy if exists quotes_tenant_delete on public.quotes;create policy quotes_tenant_delete on public.quotes for delete to authenticated using(status='draft' and private.is_active_org_user(organization_id,(select auth.uid())));
drop policy if exists quote_items_tenant_select on public.quote_items;create policy quote_items_tenant_select on public.quote_items for select to authenticated using(private.is_active_org_user(organization_id,(select auth.uid())) and exists(select 1 from public.quotes q where q.id=quote_id and q.organization_id=organization_id));
drop policy if exists quote_items_tenant_insert on public.quote_items;create policy quote_items_tenant_insert on public.quote_items for insert to authenticated with check(private.is_active_org_user(organization_id,(select auth.uid())) and exists(select 1 from public.quotes q where q.id=quote_id and q.organization_id=organization_id and q.status='draft'));
drop policy if exists quote_items_tenant_update on public.quote_items;create policy quote_items_tenant_update on public.quote_items for update to authenticated using(private.is_active_org_user(organization_id,(select auth.uid())) and exists(select 1 from public.quotes q where q.id=quote_id and q.organization_id=organization_id and q.status='draft')) with check(private.is_active_org_user(organization_id,(select auth.uid())) and exists(select 1 from public.quotes q where q.id=quote_id and q.organization_id=organization_id and q.status='draft'));
drop policy if exists quote_items_tenant_delete on public.quote_items;create policy quote_items_tenant_delete on public.quote_items for delete to authenticated using(private.is_active_org_user(organization_id,(select auth.uid())) and exists(select 1 from public.quotes q where q.id=quote_id and q.organization_id=organization_id and q.status='draft'));
create or replace function private.ws10_guard_quote_immutable() returns trigger language plpgsql set search_path=pg_catalog,public as $$begin if new.organization_id is distinct from old.organization_id or new.deal_id is distinct from old.deal_id or new.lead_id is distinct from old.lead_id or new.created_by is distinct from old.created_by or new.quote_number is distinct from old.quote_number or new.currency is distinct from old.currency or new.subtotal is distinct from old.subtotal or new.discount_total is distinct from old.discount_total or new.tax_total is distinct from old.tax_total or new.total is distinct from old.total then raise exception 'immutable quote fields cannot change';end if;if old.status='draft' and new.status not in('draft','sent') then raise exception 'invalid quote transition';elsif old.status='sent' and new.status not in('sent','accepted','rejected','expired') then raise exception 'invalid quote transition';elsif old.status='accepted' and new.status not in('accepted','sent') then raise exception 'terminal quote status';elsif old.status in('rejected','expired') and new.status is distinct from old.status then raise exception 'terminal quote status';end if;if old.status<>'draft' and (new.valid_until is distinct from old.valid_until or new.notes is distinct from old.notes) then raise exception 'issued quote content cannot change';end if;return new;end$$;
drop trigger if exists ws10_quote_immutable on public.quotes;create trigger ws10_quote_immutable before update on public.quotes for each row execute function private.ws10_guard_quote_immutable();revoke all on function private.ws10_guard_quote_immutable() from public,anon,authenticated;
create or replace function private.ws10_guard_quote_item_immutable() returns trigger language plpgsql set search_path=pg_catalog,public as $$begin if new.organization_id is distinct from old.organization_id or new.quote_id is distinct from old.quote_id or new.description is distinct from old.description or new.quantity is distinct from old.quantity or new.unit_price is distinct from old.unit_price or new.discount_percent is distinct from old.discount_percent or new.tax_percent is distinct from old.tax_percent or new.line_subtotal is distinct from old.line_subtotal or new.line_discount is distinct from old.line_discount or new.line_tax is distinct from old.line_tax or new.line_total is distinct from old.line_total then raise exception 'quote line financial fields cannot change';end if;return new;end$$;
drop trigger if exists ws10_quote_item_immutable on public.quote_items;create trigger ws10_quote_item_immutable before update on public.quote_items for each row execute function private.ws10_guard_quote_item_immutable();revoke all on function private.ws10_guard_quote_item_immutable() from public,anon,authenticated;
